image: ubuntu/19.10
packages:
  - python3
  - python3-pip
  - postgresql
environment:
  SECRET_KEY: "thisisthesecretkey"
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
tasks:
  - build: |
      cd mataroa
      pip3 install -r requirements.txt
